# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Environment
env:              dev # (dev|prod)
destination:      _gh_pages

# Server
url:              http://fauzie.github.io
baseurl:          /
timezone:         Asia/jakarta
encoding:         UTF-8

exclude:          ['package.json', 'Gruntfile.js', 'src', 'node_modules', 'Gemfile', 'Gemfile.lock']

gems:
  - jekyll-sitemap
  

### START EDITING HERE ###

# Homepage
homepage: [ about, photostack, skills, timeline, projects, services, cta, contact ]

# Main header menu
menu:
  - title: About
    url: "#about"
  - title: Skills
    url: "#skills"
  - title: Experience
    url: "#experience"
  - title: Projects
    url: "#projects"
  - title: Services
    url: "#services"
  - title: Contact
    url: "#contact"

# SEO metadata
seodata:
  shortname:        fauzie
  name:             Rizal Fauzie Ridwan
  title:            Full Stack Freelance Web Worker
  description:      Webfolio Freelancer Web Designer, Developer and Web Server Management
  keyword:          fauzie, rizal, ridwan, freelance, web, website, developer, designer, server, admin
  image:            http://fauzie.my.id/img/fauzie-banner.jpg
  twitter:          fauzievolute
  fbapp_id:         116522439772
  fbadmins:         1071962187
